// <auto-generated />
namespace http5204_mypassion_project_n00652674.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2));
        
        string IMigrationMetadata.Id
        {
            get { return "202102221440327_test2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
